import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-gray-50`}
      >
        {/* Header */}
        <header className="bg-blue-500 text-white p-4 shadow-md">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">My App</h1>
            <nav>
              <a href="/" className="px-4 py-2 hover:underline">
                Home
              </a>
              <a href="/about" className="px-4 py-2 hover:underline">
                About
              </a>
              <a href="/contact" className="px-4 py-2 hover:underline">
                Contact
              </a>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="flex-1 container mx-auto p-4">{children}</main>

        {/* Footer */}
        <footer className="bg-gray-800 text-white text-center py-4">
          <div className="container mx-auto">
            <p>&copy; 2024 My App. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
